cloud/urls.py
from django.conf.urls import url, include
from src import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^delete/(?P<file_id>[\d ]+)/$', views.delete_file, name='delete_file'),
    url(r'^download_file/(?P<file_id>[\d ]+)/$', views.download_file, name='download_file'),
    url(r'^accounts/', include('registration.backends.default.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('cloud.urls')),
    url(r'^admin/', admin.site.urls),
]

cloud/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
import os


class FileUpload(models.Model):
    file = models.FileField(null=False, blank=False, default='')
    filename = models.CharField(max_length=40)
    date_created = models.DateTimeField(auto_now_add=True)
    file_fk = models.ForeignKey(User, default=1)


@receiver(models.signals.post_delete, sender=FileUpload)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)

cloud/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import FileUpload


class FileUploadForm(forms.ModelForm):
    class Meta:
        model = FileUpload
        fields = ['file']

    def __init__(self, *args, **kwargs):
        super(FileUploadForm, self).__init__(*args, **kwargs)
        self.fields['file'].label = "Choose a file"
        self.fields['file'].required = False


class UserPasswordForm(forms.ModelForm):
    class Meta:
        model = User
        widgets = {
            'password': forms.PasswordInput(),
        }
        fields = ['password']

    def __init__(self, *args, **kwargs):
        super(UserPasswordForm, self).__init__(*args, **kwargs)
        self.fields['password'].required = False

cloud/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.utils.encoding import smart_str
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from .models import FileUpload
from .forms import FileUploadForm, UserPasswordForm
from src import settings
import os


def home(request):
    context = {
        "title": "CloudZilla",
    }
    if request.user.is_authenticated():
        return redirect(reverse('dashboard'))
    else:
        return render(request, "home.html", context)


@login_required
def dashboard(request):
    password_form = UserPasswordForm(request.POST or None, instance=request.user)
    files = FileUpload.objects.filter(file_fk=request.user.id)
    file_upload_form = FileUploadForm(request.POST or None, request.FILES or None)
    context = {
        "title": "Dashboard",
        "files": files,
        "file_upload_form": file_upload_form,
        "password_form": password_form,
    }

    if file_upload_form.is_valid() and 'add_file' in request.POST:
        instance = file_upload_form.save(commit=False)
        instance.file_fk = User.objects.get(id=request.user.id)
        minify_file_name = file_upload_form.cleaned_data.get("file")
        minify_file_name = str(minify_file_name)
        text = minify_file_name
        if len(minify_file_name) > 20:
            minify_file_name = text[0:10] + '...' + text[-10:]

        instance.filename = minify_file_name
        instance.save()
        return redirect(reverse('dashboard'))

    if password_form.is_valid() and 'new_pass' in request.POST:
        instance = password_form.save(commit=False)
        new_password = password_form.cleaned_data.get("password")
        instance.set_password(new_password)
        instance.save()
        username = request.user
        user = authenticate(username=username, password=new_password)
        login(request, user)
        return redirect(reverse('dashboard'))

    return render(request, "dashboard.html", context)


@login_required
def delete_file(request, file_id=None):
    file = FileUpload.objects.get(id=file_id)
    file.delete()
    return redirect(reverse('dashboard'))


@login_required
def download_file(request, file_id=None):
    file = FileUpload.objects.get(id=file_id)
    response = HttpResponse()
    response['Content-Type'] = ''
    response['Content-Disposition'] = "attachment; filename=" + file.filename
    response['X-Sendfile'] = smart_str(os.path.join(settings.MEDIA_ROOT, file.filename))
    return response

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/boostrap-jq.html
{% load staticfiles %}

<script src="{% static "javascripts/jquery-2.2.2.min.js" %}"></script>
<script src="{% static "javascripts/bootstrap.min.js" %}"></script>
<link href="{% static "stylesheets/bootstrap.min.css" %}" rel="stylesheet"/>

templates/dashboard.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block content %}
    {% include 'boostrap-jq.html' %}
    <script src="{% static "javascripts/dashboard.js" %}"></script>
    <link href="{% static 'stylesheets/dashboard.css' %}" rel="stylesheet"/>

    <div class="container dashboard-wrap ">
        <div class="row row-wrap">
            <div class="col-xs-12 col-sm-2 sidebar-wrap">
                <ul class="sidebar-nav">
                    <li>
                        {{ request.user }}
                    </li>
                    <li>
                        <a class="glyphicon glyphicon-user profile-button"> Profile</a>
                    </li>
                    <li>
                        <a class="glyphicon glyphicon-plus upload-button"> Upload</a>
                    </li>
                    <li>
                        <a href="{% url 'auth_logout' %}" class="glyphicon glyphicon-off"> Logout</a>
                    </li>
                    <div class="upload-widget">
                        <hr/>
                        <form class="form-upload fileUpload" method='POST' action='' enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ file_upload_form|crispy }}
                            <label id="file-label" for="id_file" class="col-xs-12">Choose a file</label>
                            <input class='btn btn-primary btn-xs form-upload-button' type='submit' name="add_file"
                                   value='Upload'/>
                        </form>
                    </div>

                    <div class="profile-widget">
                        <hr/>
                        <h5>Change password</h5>
                        <form method='POST' action=''>
                            {% csrf_token %}
                            {{ password_form|crispy }}
                            <input class='btn btn-primary btn-xs' type='submit' name="new_pass"/>
                        </form>
                    </div>
                </ul>
            </div>


            <div class="col-xs-12 col-sm-10 file-wrap">
                <h2>My files</h2>
                <hr/>
                <div class="col-xs-12">
                    {% for item in files %}
                        <div class="col-xs-4 file-box">
                            <div>
                                <a class="glyphicon glyphicon-file"></a>
                                <a href='{{ item.file.url }}'>{{ item.filename }}</a>
                                <a href="{% url 'delete_file' item.id %}" class="glyphicon glyphicon-trash"></a>
                                <a href="{% url 'download_file' item.id %}"
                                   class="glyphicon glyphicon-download-alt"></a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block content %}
    {% include 'boostrap-jq.html' %}
    {% include 'video-background.html' %}
    <script src="{% static "javascripts/dashboard.js" %}"></script>


    <div class="home-title">
        <h3>File Storage Site</h3>
        <div class="home-img-wrap">
            <img src="{% static 'images/round-white.png' %}">
            <img src="{% static 'images/round-white.png' %}">
            <img src="{% static 'images/round-white.png' %}">
        </div>
        <h2>CloudZilla</h2>
    </div>

    <div class="home-buttons">
        <div class="btn-group-vertical">
            <a href="{% url 'auth_login' %}">
                <button class="btn-login btn btn-custom">LOGIN</button>
            </a>
            <a href="{% url 'registration_register' %}">
                <button class="btn-join btn btn-custom">JOIN</button>
            </a>
        </div>
    </div>




{% endblock %}

templates/video-background.html
{% load staticfiles %}

<link href="{% static 'stylesheets/home.css' %}" rel="stylesheet"/>
<video class="video-bg" id='video' autoplay muted loop>
    <source src="{% static "videos/bgvideo.webm" %}" type="video/webm">
    Your browser does not support the video tag.
</video>

<script type="text/javascript">
    var myVideo = document.getElementById('video');
    if (typeof myVideo.loop == 'boolean') { // loop supported
        myVideo.loop = true;
    }
    else { // loop property not supported
        myVideo.on('ended', function () {
            this.currentTime = 0;
            this.play();
        }, false);
    }
    myVideo.play();
</script>